image: python:3.9  # Use a specific Python version

pipelines:
  default:
    - step:
        name: "Deploy Instagram Downloader Bot"
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y libexpat1
          - pip install --upgrade pip
          - pip install --upgrade instaloader
          - pip install python-telegram-bot
          - pip install telebot
          - apt-get install -y python3 libexpat1 
          - pip install --upgrade pip
          - pip install beautifulsoup4
          - pip install instaloader
          - pip install yt-dlp
          - python3 ig.py  

